# linlog © Fabian Lukas Grubmüller 2026
# Licensed under the EUPL

[package]
name = "linlog"
description = "A linear logic suite for all your needs."
version = "0.1.0"
edition = "2024"
license = "EUPL-1.2"

[dependencies]
foldhash = "0.1.5"
krilla = { version = "0.8.2", optional = true }
krilla-svg = { version = "0.8.1", optional = true }
png = { version = "0.18.1", optional = true }
rayon = { version = "1.12.0", optional = true }
resvg = { version = "0.47", default-features = false, features = [
  "text",
], optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = "2.0.17"
unicode-ident = "1.0.26"
unicode-normalization = { version = "0.1.25", default-features = false }

[features]
default = ["interactive", "latex", "parse", "rocq", "serialize", "svg", "typst"]
interactive = []
latex = []
parse = []
rocq = []
serialize = ["dep:serde"]
svg = []
typst = []
parallel = ["dep:rayon"]
pdf = ["svg", "dep:resvg", "dep:krilla", "dep:krilla-svg"]
png = ["svg", "dep:resvg", "dep:png"]

[lints]
workspace = true

[dev-dependencies]
roxmltree = { version = "0.21.1", default-features = false, features = ["std"] }
serde_json = "1.0.149"
